buildscript {
    repositories {
        google()
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy {
            force 'org.bouncycastle:bcprov-jdk18on:1.77'
            force 'org.bouncycastle:bcpkix-jdk18on:1.77'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath 'com.google.gms:google-services:4.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy {
            force 'org.bouncycastle:bcprov-jdk18on:1.77'
            force 'org.bouncycastle:bcpkix-jdk18on:1.77'
        }
    }
}

subprojects {
    configurations.all {
        resolutionStrategy {
            force 'org.bouncycastle:bcprov-jdk18on:1.77'
            force 'org.bouncycastle:bcpkix-jdk18on:1.77'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
